apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: pod-crashloop-alert
  labels:
    release: kube-prom-stack
spec:
  groups:
    - name: pod.rules
      rules:
        - alert: PodCrashLooping
          expr: kube_pod_container_status_waiting_reason{reason="CrashLoopBackOff"} > 0
          for: 1m
          labels:
            severity: critical
          annotations:
            summary: "Pod is in CrashLoopBackOff"
            description: "Pod {{ $labels.pod }} in namespace {{ $labels.namespace }} is crashing repeatedly."
