apiVersion: apps/v1
kind: Deployment
metadata:
  name: banking-frontend
  namespace: banking-app
  labels:
    app: banking-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: banking-frontend
  template:
    metadata:
      labels:
        app: banking-frontend
    spec:
      containers:
      - name: frontend
        image: your-dockerhub-username/banking-frontend:latest
        ports:
        - containerPort: 80
