apiVersion: v1
kind: Service
metadata:
  name: banking-frontend-service
  namespace: banking-app
spec:
  selector:
    app: banking-frontend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer  # Use NodePort if you're not on a cloud provider
