apiVersion: v1
kind: Secret
metadata:
  namespace: banking-app
  name: banking-app-secret
type: Opaque
stringData:
  MONGO_URI: "mongodb+srv://<username>:<password>@cluster0.mongodb.net/banking-system"
  JWT_SECRET: "itssecret"
