apiVersion: v1
kind: Secret
metadata:
  namespace: banking-app
  name: banking-app-secret
type: Opaque
stringData:
  SPRING_DATASOURCE_URL: "jdbc:mysql://mybankdb.cu14syugasqf.us-east-1.rds.amazonaws.com:3306/banking_system_db?useSSL=false&serverTimezone=UTC"
  SPRING_DATASOURCE_USERNAME: "adminuser"
  SPRING_DATASOURCE_PASSWORD: "YourStrongPassword123!"
  SPRING_DATASOURCE_DRIVER_CLASS_NAME: "com.mysql.cj.jdbc.Driver"
  SPRING_JPA_HIBERNATE_DDL_AUTO: "update"
  SPRING_JPA_SHOW_SQL: "true"
  SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: "org.hibernate.dialect.MySQL8Dialect"
  JWT_SECRET: "itssecret"