apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: banking-app
  name: banking-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: banking-backend
  template:
    metadata:
      labels:
        app: banking-backend
    spec:
      containers:
      - name: backend
        image: 954108257389.dkr.ecr.us-east-1.amazonaws.com/kay:17
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_DATASOURCE_URL
          valueFrom:
            secretKeyRef:
              name: banking-app-secret
              key: SPRING_DATASOURCE_URL
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              name: banking-app-secret
              key: SPRING_DATASOURCE_USERNAME
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: banking-app-secret
              key: SPRING_DATASOURCE_PASSWORD
        - name: SPRING_DATASOURCE_DRIVER_CLASS_NAME
          valueFrom:
            secretKeyRef:
              name: banking-app-secret
              key: SPRING_DATASOURCE_DRIVER_CLASS_NAME
        - name: SPRING_JPA_HIBERNATE_DDL_AUTO
          valueFrom:
            secretKeyRef:
              name: banking-app-secret
              key: SPRING_JPA_HIBERNATE_DDL_AUTO
        - name: SPRING_JPA_SHOW_SQL
          valueFrom:
            secretKeyRef:
              name: banking-app-secret
              key: SPRING_JPA_SHOW_SQL
        - name: SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT
          valueFrom:
            secretKeyRef:
              name: banking-app-secret
              key: SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: banking-app-secret
              key: JWT_SECRET
