# backend-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: banking-app
  name: banking-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: banking-backend
  template:
    metadata:
      labels:
        app: banking-backend
    spec:
      containers:
      - name: backend
        image: 954108257389.dkr.ecr.us-east-1.amazonaws.com/kay:14
        ports:
        - containerPort: 8081
        env:
        - name: SPRING_DATA_MONGODB_URI
          valueFrom:
            secretKeyRef:
              name: banking-app-secret
              key: MONGO_URI
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: banking-app-secret
              key: JWT_SECRET
