apiVersion: v1
kind: Service
metadata:
  name: banking-backend-service
  namespace: banking-app
spec:
  selector:
    app: banking-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
