
name: Frontend Deployment

on:
  push:
    branches: 
      - main
    paths:
      - app/BankingSystemFrontend/**
      - .github/workflows/frontend.deployment.yaml


jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
      actions: read


    steps:
    - name: Checkout source
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.PAT_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Configure AWS credentials (OIDC)
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::${{secrets.AWS_ACCOUNT_ID}}:role/${{secrets.ROLE_NAME}}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Log in to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build and Push Docker image
      run: |
        IMAGE_TAG=${{ github.run_number }}
        IMAGE_URI=${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.FRONTEND_ECR_REPOSITORY }}:$IMAGE_TAG
        docker build -f app/BankingSystemFrontend/Dockerfile -t $IMAGE_URI app/BankingSystemFrontend
        docker push $IMAGE_URI

    - name: Replace image tag in deployment.yaml
      run: |
        IMAGE_TAG=${{ github.run_number }}
        IMAGE_URI=${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPOSITORY }}:$IMAGE_TAG
        sed -i "s|image: .*|image: $IMAGE_URI|" argocd/backend/deployment.yaml
        echo "IMAGE_URI=$IMAGE_URI" >> $GITHUB_ENV

    - name: Commit updated deployment.yaml
      run: |
        git config user.email "boatengkwasi0303@gmail.com"
        git config user.name "Kwasi B"
        git add argocd/backend/deployment.yaml
        git commit -m "Update image tag to $IMAGE_TAG"
        git push
